mobile version skeleton
HammadSiddique/My-Portfolio pull request #1
Opened 2022-03-16 19:43 UTC by HammadSiddique

For our portfolio, the first project was to build our portfolio's mobile skeleton. Let me know if this needs any changes.

2022-03-16 22:48 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @HammadSiddique,

Nice job, you are almost there.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- You documented your work professionally. :heavy_check_mark:
- All linters checks are ok. :heavy_check_mark:

## (Changes Required) Aspects to improve: ♻️

- [x] Inside the README file please add the License section to make it more professional and kindly remove the `Author 2` part and please add your name instead of the `Author 1` title.

![image](https://user-images.githubusercontent.com/68796232/158698982-e6ad3668-df34-429c-adb9-f3aaa3102129.png)

- [ ] Nice job adding meaningful commit messages but next time please remember to capitalize the first letter of your message.

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-03-16 22:48 UTC, Omar-Muhamad commented on index.html
> +                My Logo
Kindly add the logo inside an `<a>` tag because it will be better semantically that way.

2022-03-16 22:48 UTC, Omar-Muhamad commented on index.html
> +            <h2 class="name">I'm Hammad</h2>
- [ ] Please add this title inside `<h1>` tag instead of `<h2>` because it will be better semantically that way.

2022-03-16 22:48 UTC, Omar-Muhamad commented on index.html
> +        </section>
- [ ] kindly add social icons like the given design The icons should be in a `<ul>` tag to group them, and `<li>` per icon; each icon has a link (`<a>` tag)

![image](https://user-images.githubusercontent.com/68796232/158702371-127b1e8f-025a-468a-b03a-66a57acea9c6.png)

2022-03-16 22:48 UTC, Omar-Muhamad commented on index.html
> +        </section>
- [ ] Please use flexbox for each part `header` and `section` to align its items.
- [ ] Kindly make sure you use the right margins, font sizes, and font weights, try to stick as much as possible to the given design.
- [ ] Please add your background image to this `section` and make it appear like the desgin.
Try his [link](https://www.w3schools.com/cssref/pr_background-position.asp) will help.

![image](https://user-images.githubusercontent.com/68796232/158703159-6de8aad0-bdfc-481e-b045-d4ac4efa575e.png) 
![image](https://user-images.githubusercontent.com/68796232/158703296-4348ec14-1801-4692-99c0-629a2fa9e477.png)

2022-03-17 17:38 UTC, CollinsTatang approved these changes
Hi @HammadSiddique, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![image](https://user-images.githubusercontent.com/55596970/158098566-50966056-ce3d-4c4b-aac3-cce7a7d107fb.png)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-17 18:24 UTC, merged