Added Contact form to mobile version of Portfolio
HammadSiddique/My-Portfolio pull request #3
Opened 2022-03-22 18:38 UTC by HammadSiddique

We added a contact form to the mobile version of the portfolio according to the requirements in the project.

2022-03-22 19:11 UTC, AmaduKamara requested changes
# Status: Required Changes ♻️♻️♻️ 

Hi @HammadSiddique  and @yayweb4everyone 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

![AlonzoLeroneThisCloseGIF](https://user-images.githubusercontent.com/50941074/159557355-8ed5bea5-fa76-4bcd-9c59-752157d16c22.gif)


## Highlights
✔️ Linters are working fine
✔️ Project is working
✔️ Form is working fine

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-22 19:11 UTC, AmaduKamara commented on css/style.css
> +  margin-top: 10%;
- [x] It would be nice you adjust the padding-top of this section to match the same spacing in  the Figma design

Your Design
![image](https://user-images.githubusercontent.com/50941074/159556109-6ae90672-8dd5-4550-bed5-96ba731e8c72.png)

The Figma design
![image](https://user-images.githubusercontent.com/50941074/159556331-b7858190-15ed-436f-8f8f-8dcb42374e00.png)

2022-03-22 19:11 UTC, AmaduKamara commented on css/style.css
> +  font-weight: 500;
- [x] Please add interaction to the button as requested in the project requirement
> Implement the button interactions (enable, hover, etc.). ( From the project requirements ) 👍

2022-03-22 19:24 UTC, yayweb4everyone commented
Its not too much . Stay motivated and do it right now not tommorrow.

On Tue, 22 Mar 2022, 10:12 pm Amkam, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> Status: Required Changes ♻️♻️♻️
>
> Hi @HammadSiddique <https://github.com/HammadSiddique> and
> @yayweb4everyone <https://github.com/yayweb4everyone>
>
> Good job so far! 👍
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
>
> [image: AlonzoLeroneThisCloseGIF]
> <https://user-images.githubusercontent.com/50941074/159557355-8ed5bea5-fa76-4bcd-9c59-752157d16c22.gif>
> Highlights
>
> ✔️ Linters are working fine
> ✔️ Project is working
> ✔️ Form is working fine
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In css/style.css
> <https://github.com/HammadSiddique/My-Portfolio/pull/3#discussion_r832529248>
> :
>
> > +  align-items: center;
>
> +  padding: 10px;
>
> +  margin-top: 10%;
>
>
>
>    - It would be nice you adjust the padding-top of this section to match
>    the same spacing in the Figma design
>
> Your Design
> [image: image]
> <https://user-images.githubusercontent.com/50941074/159556109-6ae90672-8dd5-4550-bed5-96ba731e8c72.png>
>
> The Figma design
> [image: image]
> <https://user-images.githubusercontent.com/50941074/159556331-b7858190-15ed-436f-8f8f-8dcb42374e00.png>
> ------------------------------
>
> In css/style.css
> <https://github.com/HammadSiddique/My-Portfolio/pull/3#discussion_r832531395>
> :
>
> > +
>
> +.submit-button {
>
> +  padding: 12px 16px;
>
> +  width: 140px;
>
> +  height: 48px;
>
> +  font-weight: 500;
>
>
>
>    - Please add interaction to the button as requested in the project
>    requirement
>
> Implement the button interactions (enable, hover, etc.). ( From the
> project requirements ) 👍
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/HammadSiddique/My-Portfolio/pull/3#pullrequestreview-917747130>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOI2OSCWSCFOEXZKCOXQUJ3VBILQNANCNFSM5RLXA4EA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-03-22 20:06 UTC, HammadSiddique commented on css/style.css
> +  font-weight: 500;
I have changed my code according to the changes you recommended to me.

2022-03-22 20:23 UTC, Whoistolu commented on css/style.css
> +  font-weight: 500;
- [ ] [REQUIRED] Great job implementing some of the recommended changes by the previous reviewer, however, you have not implemented all the `button` interactions. You have only implemented the `Hover` interaction, kindly implement, `Enabled`, `Pressed`, and `Disabled`.
![Screenshot from 2022-03-22 21-20-25](https://user-images.githubusercontent.com/58692590/159569105-e964200e-5028-4230-835d-dce8183e9c98.png)

2022-03-22 20:24 UTC, Whoistolu requested changes
Hi @HammadSiddique 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-23 08:15 UTC, HammadSiddique commented on css/style.css
> +  font-weight: 500;
@Whoistolu I have implemented all the button interactions, however, the disabled one only works, when you add the property **disabled** in HTML. If I add that property in my index.html, the button does not work and doesn't submit the form.

2022-03-23 12:36 UTC, moise10r approved these changes
### Hi @HammadSiddique, 👋 

# STATUS: Approved  🎉 

Great work on making the changes requested by a previous reviewer :1st_place_medal:  
 Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @moise10r when you comment so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-23 12:37 UTC, merged